-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 22:45:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` INT NULL DEFAULT NULL,
  `codigo_postal` INT NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `data_registre` DATETIME NULL DEFAULT NULL,
  `id_cliente1` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PROVEIDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PROVEIDOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PROVEIDOR` (
  `idProveidor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `nif` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `telefon` INT NULL DEFAULT NULL,
  `fax` INT NULL DEFAULT NULL,
  `carrer` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `pis` VARCHAR(45) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `porta` VARCHAR(45) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `ciutat` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `codi_postal` INT NULL DEFAULT NULL,
  `pais` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`idProveidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ULLERES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ULLERES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ULLERES` (
  `id_ulleres` INT NOT NULL AUTO_INCREMENT,
  ` marca` VARCHAR(45) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `color_montura` VARCHAR(45) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `g_izq` INT NULL DEFAULT NULL,
  `g_der` INT NULL DEFAULT NULL,
  `color_izq` VARCHAR(45) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `color_der` VARCHAR(45) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `proveidor_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ulleres`),
  INDEX `proveidor_id_idx` (`proveidor_id` ASC) VISIBLE,
  CONSTRAINT `proveidor_id`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `mydb`.`PROVEIDOR` (`idProveidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FLOTANT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FLOTANT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FLOTANT` (
  `ulleres_id` INT NOT NULL,
  PRIMARY KEY (`ulleres_id`),
  CONSTRAINT `ulleres_id`
    FOREIGN KEY (`ulleres_id`)
    REFERENCES `mydb`.`ULLERES` (`id_ulleres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`METALICA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`METALICA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`METALICA` (
  `ulleres_id2` INT NOT NULL,
  PRIMARY KEY (`ulleres_id2`),
  CONSTRAINT `ulleres_id2`
    FOREIGN KEY (`ulleres_id2`)
    REFERENCES `mydb`.`ULLERES` (`id_ulleres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PASTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PASTA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PASTA` (
  `ulleres_id3` INT NOT NULL,
  PRIMARY KEY (`ulleres_id3`),
  CONSTRAINT `ulleres_id3`
    FOREIGN KEY (`ulleres_id3`)
    REFERENCES `mydb`.`ULLERES` (`id_ulleres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ULLERES_has_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ULLERES_has_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ULLERES_has_CLIENTE` (
  `ULLERES_id_ulleres` INT NOT NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  `nom_empleada` VARCHAR(45) COLLATE 'utf8mb3_spanish_ci' NULL DEFAULT NULL,
  `data_venta` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ULLERES_id_ulleres`, `CLIENTE_id_cliente`),
  INDEX `fk_ULLERES_has_CLIENTE_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  INDEX `fk_ULLERES_has_CLIENTE_ULLERES1_idx` (`ULLERES_id_ulleres` ASC) VISIBLE,
  CONSTRAINT `fk_ULLERES_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`CLIENTE` (`id_cliente`),
  CONSTRAINT `fk_ULLERES_has_CLIENTE_ULLERES1`
    FOREIGN KEY (`ULLERES_id_ulleres`)
    REFERENCES `mydb`.`ULLERES` (`id_ulleres`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
